
FROM nvcr.io/nvidia/pytorch:23.11-py3-igpu

WORKDIR /home
COPY requirements.txt /home/

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

COPY client.py /home/
COPY data /home/data

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "client.py"]

